steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python Version: 3.9'

- script: |
    echo "Downloading Databricks CLI last version..."
    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    chmod +x databricks
    sudo mv databricks /usr/local/bin/databricks

    echo "Verifying Databricks CLI version..."
    databricks version
  displayName: 'Install Databricks CLI last version (Binary)'